version: "3.8"

services:
  postgres:
    container_name: vitnode_postgres
    image: postgres:16.2-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vitnode
    command: ["postgres", "-c", "log_statement=all"] # log all sql queries
    volumes:
      - ./docker/test/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vitnode

  pgadmin:
    container_name: vitnode_pgadmin
    image: dpage/pgadmin4:latest
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - vitnode

  redis:
    container_name: vitnode_redis
    image: redis:7.2.4-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - vitnode

  backend:
    container_name: vitnode_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=vitnode
      - LOGIN_TOKEN_SECRET=SECRET
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - vitnode
    volumes:
      - ./frontend/config:/frontend/config # config
      - ./frontend/themes:/frontend/themes # themes
      - ./frontend/langs:/frontend/langs # langs
      - ./backend/public:/app/public # static files

  frontend:
    container_name: vitnode_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_GRAPHQL_URL=http://backend:8080
        - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - vitnode
    volumes:
      - ./frontend/config:/app/config # config
      - ./frontend/themes:/app/themes # themes
      - ./frontend/langs:/app/langs # langs

networks:
  vitnode:
# volumes:
#   frontend_data:
