version: '3.8'

services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - '3000:3000'

  postgres:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vitnode
    command: ['postgres', '-c', 'log_statement=all']
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'

  redis:
    image: redis:7.2.3-alpine
    restart: always
    ports:
      - '6379:6379'
# volumes:
#   db:
#     driver: local
