version: "3.8"

services:
  postgres:
    container_name: vitnode_postgres_dev
    image: postgres:16.2-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vitnode
    command: ["postgres", "-c", "log_statement=all"] # log all sql queries
    volumes:
      - ./docker/dev/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vitnode_dev

  pgadmin:
    container_name: vitnode_pgadmin_dev
    image: dpage/pgadmin4:latest
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - vitnode_dev

networks:
  vitnode_dev:
