version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vitnode
    command: ['postgres', '-c', 'log_statement=all'] # log all sql queries
    volumes:
      - ./docker/dev/database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - vitnode

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - vitnode

  redis:
    image: redis:7.2.3-alpine
    restart: on-failure
    ports:
      - '6379:6379'
    networks:
      - vitnode

networks:
  vitnode:
