name: Tests & Builds

on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npx run backend:init
      - run: npm run lint
      - run: npm run backend:build --if-present
      - run: npm run frontend:build --if-present
